name: event_object
description: >-
  This package will help you to create and manage events,
  by creating event objects that fires with payload.

version: 1.1.0
repository: https://github.com/Davenchy/event_object

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
